"""
LogSentinel - Detection Engine

Applies detection rules against parsed LogEvents and generates Alerts.
Supports three rule types:
  - threshold: Count events matching criteria within a time window
  - pattern: Match regex patterns against specific event fields
  - correlation: Correlate related events across time
"""

import re
from collections import defaultdict
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Optional

import yaml

from .models import Alert, LogEvent


class DetectionEngine:
    """Core detection engine that applies rules against parsed log events."""

    def __init__(self, rules_config: Optional[str] = None):
        """
        Initialize the detection engine.

        Args:
            rules_config: Path to YAML rules config file. If None, uses default path.
        """
        self.rules: list[dict[str, Any]] = []
        if rules_config:
            self._load_rules(rules_config)

    def _load_rules(self, config_path: str) -> None:
        """Load detection rules from a YAML configuration file."""
        path = Path(config_path)
        if not path.exists():
            raise FileNotFoundError(f"Rules config not found: {config_path}")

        with open(path, "r") as f:
            data = yaml.safe_load(f)

        self.rules = data.get("rules", [])

    def analyze_events(self, events: list[LogEvent]) -> list[Alert]:
        """
        Analyze a list of parsed log events and generate alerts.

        Args:
            events: List of parsed LogEvent objects.

        Returns:
            List of Alert objects generated by the detection rules.
        """
        if not self.rules:
            return []

        alerts: list[Alert] = []

        for rule in self.rules:
            detection_type = rule.get("detection_type", "")
            log_source = rule.get("log_source", "")

            # Filter events by the rule's target log source
            source_events = [e for e in events if e.source == log_source]
            if not source_events:
                continue

            if detection_type == "threshold":
                rule_alerts = self._check_threshold_rule(rule, source_events)
            elif detection_type == "pattern":
                rule_alerts = self._check_pattern_rule(rule, source_events)
            elif detection_type == "correlation":
                rule_alerts = self._check_correlation_rule(rule, source_events)
            else:
                continue

            alerts.extend(rule_alerts)

        return alerts

    def _check_threshold_rule(self, rule: dict[str, Any], events: list[LogEvent]) -> list[Alert]:
        """
        Check threshold-based rules.
        Groups events by IP and counts occurrences within the time window.
        """
        rule_id = rule["rule_id"]
        severity = rule["severity"]
        conditions = rule.get("conditions", {})
        event_type = conditions.get("event_type", "")
        threshold = conditions.get("threshold", 5)
        time_window = conditions.get("time_window_seconds", 60)
        unique_users_threshold = conditions.get("unique_users_threshold")

        # Filter events by the required event_type
        filtered = [e for e in events if e.parsed.get("event_type") == event_type]
        if not filtered:
            return []

        # Group by source IP
        ip_groups: dict[str, list[LogEvent]] = defaultdict(list)
        for event in filtered:
            ip = event.parsed.get("ip", "unknown")
            ip_groups[ip].append(event)

        alerts: list[Alert] = []

        for ip, ip_events in ip_groups.items():
            # Sort events by timestamp
            ip_events.sort(key=lambda e: e.timestamp)

            # Check if this is a unique-users threshold rule (DET-007)
            if unique_users_threshold is not None:
                # Apply sliding time window for unique user enumeration detection
                for i in range(len(ip_events)):
                    window_end = ip_events[i].timestamp + timedelta(seconds=time_window)
                    window_events = [
                        e for e in ip_events[i:]
                        if e.timestamp <= window_end
                    ]
                    unique_users = set()
                    for e in window_events:
                        user = e.parsed.get("user", "")
                        if user:
                            unique_users.add(user)
                    if len(unique_users) >= unique_users_threshold:
                        alert = Alert(
                            rule_id=rule_id,
                            title=rule["title"],
                            severity=severity,
                            source_ip=ip,
                            events=window_events,
                            count=len(window_events),
                            description=rule.get("description", ""),
                            mitre_technique=rule.get("mitre_technique", ""),
                            recommendation=rule.get("recommendation", ""),
                        )
                        alerts.append(alert)
                        break
                continue

            # Sliding window check for standard threshold rules
            for i in range(len(ip_events)):
                window_end = ip_events[i].timestamp + timedelta(seconds=time_window)
                count_in_window = sum(
                    1 for e in ip_events[i:]
                    if e.timestamp <= window_end
                )
                if count_in_window >= threshold:
                    window_events = [
                        e for e in ip_events[i:]
                        if e.timestamp <= window_end
                    ]
                    alert = Alert(
                        rule_id=rule_id,
                        title=rule["title"],
                        severity=severity,
                        source_ip=ip,
                        events=window_events,
                        count=count_in_window,
                        description=rule.get("description", ""),
                        mitre_technique=rule.get("mitre_technique", ""),
                        recommendation=rule.get("recommendation", ""),
                    )
                    alerts.append(alert)
                    break  # One alert per IP per detection pass

        return alerts

    def _check_pattern_rule(self, rule: dict[str, Any], events: list[LogEvent]) -> list[Alert]:
        """
        Check pattern-based rules.
        Applies regex patterns against specific fields in events.
        """
        rule_id = rule["rule_id"]
        severity = rule["severity"]
        conditions = rule.get("conditions", {})
        field = conditions.get("field", "path")
        patterns = conditions.get("patterns", [])

        # Compile patterns
        compiled_patterns = [re.compile(p) for p in patterns]

        alerts: list[Alert] = []

        for event in events:
            target_value = event.parsed.get(field, "")
            if not target_value:
                continue

            for pattern in compiled_patterns:
                if pattern.search(target_value):
                    ip = event.parsed.get("ip", "")
                    alert = Alert(
                        rule_id=rule_id,
                        title=rule["title"],
                        severity=severity,
                        source_ip=ip,
                        events=[event],
                        count=1,
                        description=rule.get("description", ""),
                        mitre_technique=rule.get("mitre_technique", ""),
                        recommendation=rule.get("recommendation", ""),
                    )
                    alerts.append(alert)
                    break  # One alert per event per rule

        return alerts

    def _check_correlation_rule(self, rule: dict[str, Any], events: list[LogEvent]) -> list[Alert]:
        """
        Check correlation-based rules.
        Looks for sequences of related events (e.g., failed sudo -> successful sudo)
        within a configurable time window.
        """
        rule_id = rule["rule_id"]
        severity = rule["severity"]
        conditions = rule.get("conditions", {})
        event_type = conditions.get("event_type", "")
        failure_keyword = conditions.get("failure_keyword", "")
        time_window = conditions.get("time_window_seconds", 0)  # 0 = no window limit

        # Filter for the target event type
        typed_events = [e for e in events if e.parsed.get("event_type") == event_type]
        if not typed_events:
            return []

        alerts: list[Alert] = []

        # Group events by user
        user_groups: dict[str, list[LogEvent]] = defaultdict(list)
        for event in typed_events:
            user = event.parsed.get("user", "unknown")
            user_groups[user].append(event)

        for user, user_events in user_groups.items():
            user_events.sort(key=lambda e: e.timestamp)

            # Look for pattern: failure followed by success within time window
            has_failure = False
            failure_start_time: Optional[datetime] = None
            failure_events: list[LogEvent] = []
            ip = ""

            for event in user_events:
                message = event.parsed.get("message", "")
                sudo_result = event.parsed.get("sudo_result", "")
                ip = event.parsed.get("ip", ip) or ip

                if sudo_result == "failed" or failure_keyword in message:
                    has_failure = True
                    failure_events.append(event)
                    if failure_start_time is None:
                        failure_start_time = event.timestamp
                elif sudo_result == "success" and has_failure:
                    # Check if the success happened within the time window
                    if time_window > 0 and failure_start_time:
                        elapsed = (event.timestamp - failure_start_time).total_seconds()
                        if elapsed > time_window:
                            # Outside the time window - reset and continue
                            has_failure = False
                            failure_events = []
                            failure_start_time = None
                            continue

                    # Privilege escalation pattern detected
                    alert = Alert(
                        rule_id=rule_id,
                        title=rule["title"],
                        severity=severity,
                        source_ip=ip,
                        events=failure_events + [event],
                        count=len(failure_events) + 1,
                        description=rule.get("description", ""),
                        mitre_technique=rule.get("mitre_technique", ""),
                        recommendation=rule.get("recommendation", ""),
                    )
                    alerts.append(alert)
                    has_failure = False
                    failure_events = []
                    failure_start_time = None

        return alerts
