"""
LogSentinel - Data Models

Defines the core data structures used throughout the LogSentinel pipeline:
LogEvent, Alert, and Report.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass
class LogEvent:
    """A single parsed log entry from any supported log source."""

    timestamp: datetime
    source: str  # 'auth.log', 'access.log', 'syslog'
    raw: str  # Original raw log line
    parsed: dict[str, Any] = field(default_factory=dict)  # Extracted fields
    host: str = ""


@dataclass
class Alert:
    """A security alert generated by the detection engine."""

    rule_id: str  # e.g., 'DET-001'
    title: str  # e.g., 'SSH Brute Force Detected'
    severity: str  # 'Critical', 'High', 'Medium', 'Low'
    source_ip: str = ""
    events: list[LogEvent] = field(default_factory=list)
    count: int = 0
    timestamp: datetime = field(default_factory=datetime.now)
    mitre_technique: str = ""
    recommendation: str = ""
    description: str = ""


@dataclass
class Report:
    """Complete analysis report containing scan metadata and all alerts."""

    scan_time: datetime = field(default_factory=datetime.now)
    total_events: int = 0
    total_alerts: int = 0
    alerts: list[Alert] = field(default_factory=list)
    summary: dict[str, Any] = field(default_factory=dict)
    input_files: list[str] = field(default_factory=list)
